# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "forwarded_port", guest: 80, host: 3000
  config.vm.network "private_network", ip: "33.33.33.1"

  config.vm.synced_folder "../project", "/var/www/html/project", :mount_options => ['dmode=777', 'fmode=777']

  # config.vm.provision :shell, path: "script/bootstrap.sh"
  config.vm.provision :shell, path: "script/install_lamp.sh"
  config.vm.provision :shell, path: "script/install_drupal.sh"

end
